nodejs:
  nameOverride: nazuna-uat
  serviceNameSuffix: service
  replicaCount: 3
  image:
    repository: opsta/nazuna
    tag: uat
    pullPolicy: Always
  containerPorts:
    - 8081
  env:
    - name: NODE_ENV
      value: uat
    - name: NODE_GRAYLOG_HOST
      value: graylog.demo.opsta.co.th
    - name: NODE_GRAYLOG_PORT
      value: 12201
    - name: NODE_STATSD_HOST
      value: statsd.demo.opsta.co.th
    - name: NODE_STATSD_PORT
      value: 8125
    - name: NODE_STATSD_PREFIX
      value: uat_nazuna_
    - name: NODE_INFLUXDB_URI
      value: http://influxdb.demo.opsta.co.th:8086/statsd
  healthCheck:
    path: /
    port: 8081
  type: NodePort
  default:
    ports:
      - name: nazuna-http
        externalPort: 8081
        internalPort: 8081
        protocol: TCP
